# Generated by Django 4.2.21 on 2025-05-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporttype',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='sporttype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='sport_type_icons/'),
        ),
    ]
